### ISSUE TITLE
Catenary curve validation

### ISSUE THREAD

**Issue by armantekinalp** [GazzolaLab/PyElastica#230] opened 2023-02-23 17:12 UTC
@Ali-7800 will include a new validation case for PyElastica, by comparing simulations with analytical solution.

**Comment by erfanhamdi** [comment] 2023-04-29 12:07
Hello everyone

I wanted to know if I can work on this issue as I am starting to learn more about the pyElastica package and would love to be able to contribute!

**Comment by armantekinalp** [comment] 2023-05-01 18:51
Hi @erfanhamdi 

Thank you for your interest. You can go ahead and start implementing this case and create a PR when you are done together with simulation analytical comparison plots.

**Comment by armantekinalp** [comment] 2023-05-16 02:48
@erfanhamdi Are you still interested in this issue?

**Comment by erfanhamdi** [comment] 2023-05-16 06:17
I have simulated the catenary beam case and also the catenary chain but the problem is with the validation. I am not sure what should I use for it as there is an elastic catenary concept which seems to be closer to the catenary using one beam and there is this classical catenary which is defined for chains and ropes.
do you have any idea on that?

**Comment by armantekinalp** [comment] 2023-06-02 15:47
@erfanhamdi how is this issue going? Do you have any questions?

**Comment by cuicw** [comment] 2024-01-30 13:32
Hello, I have some questions to ask. When the catenary is modeled, is the initial configuration of your curve a random straight rod, and then the catenary configuration that appears through iteration

**Comment by cuicw** [comment] 2024-01-30 13:34
Hello, I have some questions to ask. When the catenary is modeled, is the initial configuration of your curve a random straight rod, and then the catenary configuration that appears through iteration

**Comment by armantekinalp** [comment] 2024-01-30 14:39
You can start with a straight rod. As the simulation progress rod approaches to catenary shape.

**Comment by Ali-7800** [comment] 2024-02-23 20:27
Example added, closing issue now.

**Closed by Ali-7800** 2024-02-23 20:27 UTC
Labels: enhancement, prio:high
